### ISSUE TITLE
[Discussion] So can I use this repo to train a full scale poker strategy?

### ISSUE THREAD

**Issue by andyafter** [pandaant/poker-cfrm#1]
So which game have this repo been used for? And what about the training requirement(CPU cores, etc.) and the performance?

**Comment by pandaant** [comment]
This repo can be used for a variety of games. In the /games folder you can find some game definitions for Limit, No Limit Holdem, Leduc and Kuhn Poker. Personally i've used it to compute some strategies for NLTH. 

The training requirements scale with the size and type of abstractions you choose. The larger the game tree the more computing power and RAM will be required. My setup used 8 Cores and 16Gb of ram (which was not enough to let some of my larger abstractions converge in a reasonable amount of time). You can pass the number of threats you want to use as a parameter. See the /scripts folder for some example configurations.

**Comment by andyafter** [comment]
Hey mark, my understanding is that this repo considers 4 actions(bet sizes) at each info node. So I ran the cfrm on a 64 core 128GB computer for 3 days and got the regret file. The regret file should be already a strategy set that I can use to play no limit right? I am still trying to understand how could I use that file so that I can play with it.

**Comment by pandaant** [comment]
Hey, the number of actions at each info node depends on your configuration. It is possible to have more or less than 4. 
As for the question about using the generated strategy: Have a look at src/player-main.cpp. The player binary can be used to load a strategy and use it to play using the UAPRG server. I noticed that i cant find the server online anymore. Maybe it has been discontinued. I will have a look if i can find it in my old sources.

**Comment by voraz415** [comment]
How does cfrm handle situations where there are infinite equilibrium strategies, for example the player first to act in kuhn poker?  Will it just arbitrarily converge to a single strategy?

**Comment by pandaant** [comment]
It's been a long time since i've worked on these problems. But i'd say it arbitrarily converges to a single strategy.

**Comment by pandaant** [comment]
@andyafter I had another look and found the server code [here](http://www.computerpokercompetition.org/repos/project_acpc_server/trunk/). Sorry for the delay!
