### ISSUE TITLE
Card abstraction - Potential Aware

### ISSUE THREAD

**Issue by Emualliug2705** [pandaant/poker-cfrm#2]
Hi Pandaant, 
Nice work ! I would like to know if you implemented the "P for the potential aware abstraction" because i don't see it in the code available in github. 
If i use cluster_abs with -m mixed_npeo it just computes with the mixed_nooo abstraction, you have something wrote like that in the scripts directory.

The github's files are updated? 
I have a particular interest in this algorithm.

Thanks for your time

**Comment by pandaant** [comment]
Hi Emualliug, 

it's been a long time i've worked on this code, but i believe the potential abstraction is computed a step after what you are describing. 
Also there is no mixed_npeo for the cluster-abs binary. I probably explained it badly in the readme but only the combinations mentioned there are currently supported. The P for potential comes in at the second step.

in my example script for nlth you can see the first cluster abstraction is computed to be used by the next binary to generate the potential aware abstraction. by passing "-p 1" the potential-abs computes a potential aware abstraction for the flop (2 = turn). so the original neeo becomes npeo abstraction.

To get the potential aware npeo abstraction:
1. cluster hands using cluster-abs -m mixed_neeo -s <path/to/save/cluster/abstraction>
2. potential-abs -p 1 -l <path/to/saved/cluster/abstraction> -s <path/to/save/potential/aware/abstraction>

hope that helps

**Comment by shantanukarve** [comment]
I generated ehs.dat just fine but I don't understand how ehs.dat can be used. I looked for refererences to it in the repo and apart from the generating program gen_eval_table.cpp no other code references it.

**Comment by pandaant** [comment]
Hi, 
the EHS.dat is used by the CusterAbstraction programm to generate an abstraction that can be used by the Training Algorithm. It's loaded [here](https://github.com/pandaant/poker-cfrm/blob/963b50639aea2c0ba838d067eecab9333dcdeb3c/src/cluster-abs-main.cpp#L42) and used for example [here](https://github.com/pandaant/poker-cfrm/blob/963b50639aea2c0ba838d067eecab9333dcdeb3c/src/cluster-abs-main.cpp#L131)

**Comment by shantanukarve** [comment]
Thanks very much. that resolved my issue.
