### ISSUE TITLE
MIXED_XXXX abstraction head to head win averages are in unexpected order 

### ISSUE THREAD

**Issue by shantanukarve** [pandaant/poker-cfrm#4]
I ran some tests of holdem, nolimit, 2player, 1|2 small blind |bigblind, 200|200 stack, maxRaises of 3 4 4 4 games. During cluster abstractions runs for all tests I kept the nb-samples to "0,2,500,500", the buckets to :    169,5,10,500,    the error bounds to :   .01,.01,.01,.01, the nb-hist-samples-per-round to 0,1,200,200. For all tests I held the action-abstraction to polrelative at 0.4,0.8,1.2,2,5,9999 raises. For cfr learning I had 12 threads and times of 8 hours and sometimes 16 hrs and 24 hrs.

I ran the head to heads, specifically NSSS against each of the NOOO, NEES, NEEO. I expected NSSS to perform the wost, meaning lose money, i.e. negative average wins and NEEO to be best.  I'm getting NSSS to be the best !  Here's a table of results. As you can see I ran cfr's learning phase for the most sophisticated strategy, NEEO,  for longer and longer times, so 8 hrs then 16 hours then 24 hours but that didn't change things. Any ideas of what to experiment with to get the results to align with expectations - meaning NEEO, NEES, NOOO to be all better than NSSS. 
**Update:** thinking harder, I'm wondering if the clustering abstraction is too coarse so I need to increase the fineness, by increasing the nb-samples and the nb-hist-samples. Any ideas on combinatrics around this to see what's appropriate ?

<table cellspacing="0" border="0">
	<colgroup width="44"></colgroup>
	<colgroup width="75"></colgroup>
	<colgroup width="52"></colgroup>
	<colgroup width="68"></colgroup>
	<colgroup width="62"></colgroup>
	<colgroup width="36"></colgroup>
	<colgroup width="85"></colgroup>
	<colgroup width="42"></colgroup>
	<colgroup width="85"></colgroup>
	<tr>
		<td height="47" align="left"><b>Abs</b></td>
		<td align="right"><b>cfrm runtime (secs / 1000)</b></td>
		<td align="left"><b>Abs</b></td>
		<td align="left"><b>cfrm runtime (secs / 1000)</b></td>
		<td align="left"><b>Avg win</b></td>
		<td align="left"><b>Var</b></td>
		<td align="left"><b>num games</b></td>
		<td align="left"><b>seed</b></td>
		<td align="left"><b>median win</b></td>
	</tr>
	<tr>
		<td height="17" align="left">NSSS</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NOOO</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="2.94" sdnum="1033;">2.94</td>
		<td align="right" sdval="7167" sdnum="1033;">7167</td>
		<td align="right" sdval="500000" sdnum="1033;">500000</td>
		<td align="right" sdval="7534" sdnum="1033;">7534</td>
		<td align="right" sdval="0" sdnum="1033;">0</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NOOO</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="2.76" sdnum="1033;">2.76</td>
		<td align="right" sdval="7119" sdnum="1033;">7119</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="3575" sdnum="1033;">3575</td>
		<td align="right" sdval="0" sdnum="1033;">0</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NOOO</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="2.95" sdnum="1033;">2.95</td>
		<td align="right" sdval="7163" sdnum="1033;">7163</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="8379" sdnum="1033;">8379</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEES</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="3.4" sdnum="1033;">3.4</td>
		<td align="right" sdval="7564" sdnum="1033;">7564</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="8379" sdnum="1033;">8379</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEES</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="3.03" sdnum="1033;">3.03</td>
		<td align="right" sdval="3575" sdnum="1033;">3575</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="3575" sdnum="1033;">3575</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
		<td align="left"><br></td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEEO</td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="right" sdval="5.07" sdnum="1033;">5.07</td>
		<td align="right" sdval="7475" sdnum="1033;">7475</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="8379" sdnum="1033;">8379</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEEO</td>
		<td align="right" sdval="57" sdnum="1033;">57</td>
		<td align="right" sdval="4.53" sdnum="1033;">4.53</td>
		<td align="right" sdval="7118" sdnum="1033;">7118</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="7534" sdnum="1033;">7534</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEEO</td>
		<td align="right" sdval="86" sdnum="1033;">86</td>
		<td align="right" sdval="5.05" sdnum="1033;">5.05</td>
		<td align="right" sdval="7141" sdnum="1033;">7141</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="7534" sdnum="1033;">7534</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
	<tr>
		<td height="17" align="left"><br></td>
		<td align="right" sdval="28" sdnum="1033;">28</td>
		<td align="left">NEEO</td>
		<td align="right" sdval="86" sdnum="1033;">86</td>
		<td align="right" sdval="4.84" sdnum="1033;">4.84</td>
		<td align="right" sdval="7138" sdnum="1033;">7138</td>
		<td align="right" sdval="100000" sdnum="1033;">100000</td>
		<td align="right" sdval="8370" sdnum="1033;">8370</td>
		<td align="right" sdval="1.5" sdnum="1033;">1.5</td>
	</tr>
</table>

**Comment by pandaant** [comment]
Sorry for the super late response.

Event though it's probably too late i just want to say that it's been a long time i worked on this project and i'm not too familiar with the specifics anymore. 
From what i see the update to your post is one reason. Accurate calculations for the flop are expensive and are kept very low in the example configuration file.  The cluster abstraction only uses two buckets on the flop also. Which is a very low number.
