### ISSUE TITLE
Custom clusters in potential-abs

### ISSUE THREAD

**Issue by CloneHub94** [pandaant/poker-cfrm#5]
Hi Mark,

I was wondering whether or not the potential aware abstraction you created is based on the paper: http://www.cs.cmu.edu/afs/cs/Web/People/sandholm/potential-aware_imperfect-recall.aaai14.pdf

secondly, in the readme you say that the clusters in potential-abs are pre-calculated. Is there a way to regenerate them for a custom target. For example, if I wanted to create a potential aware abstraction of {169 ,200, 200, 200} or {169 ,500, 500, 500} ext.. would this be possible somehow?

Also, is the cfrm a version of MCCFR with external sampling?

With kind regards

**Comment by pandaant** [comment]
Hey,

yes, i think the potential aware abstraction is based on the paper you posted. It's been some time i worked on this project though.

Regarding your second question: in the scripts folder is a script to generate an exemplary holdem agent with potential abstraction.
The cluster abstraction that the potential abstraction is calculated from is generated first. There is a parameter for the number of buckets to use in each betting round. I think the potential abstraction works on the same buckets defined in the cluster abstraction. I'm not entirely sure anymore if the potential abstraction can have differing amount from the cluster abstraction.

Yes the cfr sampling method can be set in row 25 of src/cfrm-main.cpp and defaults to External sampling.

**Comment by CloneHub94** [comment]
Ok so if I understand it correctly executing cluster-abs before potential-abs is a pre-requisite since potential-abs will use the buckets and nb_samples from cluster-abs when it's executed?

**Comment by pandaant** [comment]
yes, that is correct.

**Comment by CloneHub94** [comment]
OK, so the cluster-abs clusters determine how many clusters will be used to bucket information situations in potential-abs? Just 2 final questions if you don't mind. You used kmeans instead of kmeans++ that they mention in the paper. Is there a significant difference between these two approaches in your opinion? And finally, I was wondering if your code supports the use of multithreading? Since I wanted to test it out on a 64 core set up so that I could generate the data and cluster it over 64 threads?

**Comment by pandaant** [comment]
I had another look at the code and saw that potential-abs has a parameter "--nb-buckets" that specifies how many buckets to use for the round that the potential-abs will be calculated for.  The parameter "p" sets the round the potential-abs is calculated for (flop, turn, river)

I can't remember anymore why i used kmeans over kmeans++, sorry.

All binaries except player-main support multithreading. It is also used in the scripts folder. 
Also the binaries can be called with the "--help" parameter to show all their options.

**Comment by FlashPlayer13** [comment]
Hi Mark,

Am I right that potential aware abstraction makes sense only for flop (and maybe preflop) stage? 
Because on turn it is same as distribution aware approach and on river we have only OCHS option.
